wap_web/wapApp/urls.py
from django.conf.urls import url

from . import views
app_name = 'wapApp'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^user/$', views.user, name='user'),
    url(r'^base/$', views.base, name='base'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^photos/$', views.photos, name='photos'),
    url(r'^about/$', views.about, name='about'),
    url(r'^features/$', views.features, name='features'),
    url(r'^ditu/$', views.ditu, name='ditu'),#index可以去掉吗
    url(r'^regist/',views.regist,name='regist'),
    url(r'^redirectreg/',views.redirectreg,name='redirectreg'),
    url(r'^redirectlog/',views.redirectlog,name='redirectlog'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^activate/$', views.activate, name='activate'),
    url(r'^activeUser/$', views.activeUser, name='activeUser'),
    url(r'^security/$', views.security, name='security'),
    url(r'^personalCenter/$', views.personalCenter, name='personalCenter'),

]

wap_web/wap_web/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wapApp/',include('wapApp.urls'))
]

wap_web/wapApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
import ordering as ordering
from django.contrib import admin
import django.utils.timezone as timezone
from django.db import models
# Create your models here.
class Users(models.Model):
    username = models.CharField(max_length=55)
    password = models.CharField(max_length=15)
    email = models.EmailField(max_length=30)
    is_active = models.IntegerField(default=0)
    add_date = models.IntegerField('注册日期',default=0)
    active_date = models.IntegerField('激活', default=0)
    class meta:
        ordering=['-add_date']

wap_web/wapApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import time
from django.shortcuts import render,HttpResponse,render_to_response,redirect
from .models import Users as User
import json
from django.contrib import messages
from django.conf import settings as django_settings
from django.core.mail import send_mail
# Create your views here.
def index(request):
    return render(request,'../templates/wapApp/base/index.html')
def contact(request):
    return render(request,'../templates/wapApp/contact.html')
def photos(request):
    return render(request,'../templates/wapApp/photos.html')
def about(request):
    return render(request,'../templates/wapApp/about.html')
def features(request):
    return render(request,'../templates/wapApp/features.html')


def ditu(request):
    return render(request,'../templates/wapApp/ditu.html')

def user(request):
    return render(request,'../templates/wapApp/userCenter.html')
def base(request):
    return render(request,'../templates/wapApp/base.html')
def personalCenter(request):
    return render(request,'../templates/wapApp/personalCenter.html')
#注册
def redirectreg(request):
    return render(request, '../templates/wapApp/base/register.html')
def regist(request):
    user = User.objects.filter(username=request.POST['username'])
    if user.exists():
        return HttpResponse('{"status":"fail","msg":"注册失败，用户名已注册"}')
    else:
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        add_date = int(time.time())
        user = User.objects.create(username=username, password=password,email=email, add_date=add_date)
        user.is_active = 0

        # user.active_date = 0
        user.save()
        sendEmail(user)
        return HttpResponse('{"status":"success","msg":"用户注册成功"}')

def sendEmail(user):
    import smtplib
    from email.mime.text import MIMEText
    mail_host = "smtp.163.com"
    mail_user = "15805156299@163.com"
    mail_pass = "lsiya19950109"
    user_id = str(user.id)
    # username=username.encode('utf-8')
    sender = "15805156299@163.com"
    receivers = [user.email]
    content ="\n".join([u'{0},欢迎加入minio掌上商城'.format(user.username), u'请访问该链接，完成用户验证:',
	        '/'.join([django_settings.DOMAIN,'activate?id='+user_id]),u'有效激活时间是4小时内'])
    title = '激活您的掌上商城账号'
    message = MIMEText(content, 'html', 'utf-8')
    message['From'] = '掌上商城邮箱管理员'+'<'+sender+'>'
    message['To'] = ",".join(receivers)
    message['Subject'] = title
    try:
        smtpObj = smtplib.SMTP_SSL(mail_host, 465)  # 启用SSL发信, 端口一般是465
        smtpObj.login(mail_user, mail_pass)  # 登录验证
        smtpObj.sendmail(sender, receivers, message.as_string())  # 发送
        print("mail has been send successfully.")
    except smtplib.SMTPException as e:
        print(e)
def activate(request):
    # request.encoding = 'gb2312'
    user_id = int(request.GET['id'])
    # username = username.encode('utf-8')
    # import urllib.parse
    # username = urllib.parse.unquote(request.GET.get('username'),'GBK')
    # print(username)
    user_info = User.objects.get(id=user_id)
    return render(request,'../templates/wapApp/base/activate.html',{'user_info':user_info})
def activeUser(request):#激活时要确定激活的id,完善激活的严谨性
    # active_date = timezone.now()
    # User.objects.filter(id=1).update(is_active=1)
    user_info = User.objects.get(id=int(request.GET.get('user_id')))
    if(int(time.time()) > (user_info.add_date+4*24*60*3600)):
        return HttpResponse('{"status":"overtime","msg":"激活连接失效，请重新注册"}')
    else:
        user = User.objects.get(id=request.GET.get('user_id'))
        user.is_active = 1
        user.active_date = int(time.time())
        user.save()
        return HttpResponse('{"status":"activesuccess","msg":"激活成功"}')
# 登录
def redirectlog(request):
    return render(request, '../templates/wapApp/base/login.html')
def login(request):
    if request.method == 'POST':
        username = request.POST['user']
        password = request.POST['pass']
        info = User.objects.filter(username=username, password=password)
        is_active = User.objects.filter(username=username, is_active=1)
        if info.exists() and is_active.exists():
            info_dict = {'username': username}
            request.session['username'] = username
            return HttpResponse('{"status":"success"}')

        else:
            return HttpResponse('{"status":"error","msg":"登录失败"}')
    else:
        return HttpResponse('{"status":"fail","msg":"登录失败，用户名或密码错误"}')

# 登出
def logout(request):
    # request.session.set_expiry(value)过期时间
    # 如果value是一个整数，会话将在value秒没有活动后过期。
    # 如果value为0，那么用户会话的Cookie将在用户的浏览器关闭时过期。
    # 如果value为None，那么会话永不过期。
    request.session.clear()
    return render(request, '../templates/wapApp/userCenter.html')

# 账户安全界面
def security(request):

    return render(request,'../templates/wapApp/security.html')

wap_web/templates/wapApp/about.html
{% load staticfiles %}
<div class="pages">
  <div data-page="projects" class="page no-toolbar no-navbar">
    <div class="page-content">
    
     <div class="navbarpages">
       <div class="navbar_home_link"><a href="#" data-panel="left" class="open-panel"><img src="{% static 'images/icons/white/user.png' %}" alt="" title="" /></a></div>
       <div class="navbar_page_center">About</div>
       <div class="menu_open_icon_white"><a href="{% url 'wapApp:index' %}"><img src="{% static 'images/menu_open.png' %}" alt="" title="" /></a></div>
     </div>
     <div id="pages_maincontent">
      
          <h2 class="page_subtitle">About minio</h2>
          
              <div class="page_single">
              <img src="{% static 'images/page_photo.jpg' %}" alt="" title="" />
              <blockquote>
              Design can be art. Design can be aesthetics. Design is so simple, that's why it is so complicated. <span>Paul Rand</span>
              </blockquote>
              <h3>Smart features</h3>
              <ul class="features_list">
                  <li><a href="{% url 'wapApp:photos' %}"><img src="{% static 'images/icons/black/photos.png' %}" alt="" title="" /><span>Photo gallery</span></a></li>
                  <li><a href="blog.html"><img src="{% static 'images/icons/black/blog.png' %}" alt="" title="" /><span>Blog layout</span></a></li>
                  <li><a href="tabs.html"><img src="{% static 'images/icons/black/responsive.png' %}" alt="" title="" /><span>Responsive tabs</span></a></li>
                  <li><a href="toogle.html"><img src="{% static 'images/icons/black/toogle.png' %}" alt="" title="" /><span>Toogles</span></a></li>
                  <li><a href="#" data-popup=".popup-login" class="open-popup"><img src="{% static 'images/icons/black/user.png' %}" alt="" title="" /><span>User login</span></a></li>
                  <li><a href="{% url 'wapApp:contact' %}"><img src="{% static 'images/icons/black/contact.png' %}" alt="" title="" /><span>Contact form</span></a></li>
                  <li><a href="#" data-popup=".popup-social" class="open-popup"><img src="{% static 'images/icons/black/heart.png' %}" alt="" title="" /><span>Social share</span></a></li>
                  <li><a href="#" data-panel="right" class="open-panel"><img src="{% static 'images/icons/black/phone.png' %}" alt="" title="" /><span>Right slide panel</span></a></li>
              </ul>
              <div class="clear"></div> 
              <h3>Simple list</h3>
              <ul class="simple_list">
              <li>perspiciatis unde omnis</li>
              <li>voluptatem accusantium</li>
              <li>doloremque laudantium</li>
              </ul>
              <p>
              Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
              </p>
              <a href="#" class="button_full">Full width button</a>
              </div>
      
      </div>
      
      
    </div>
  </div>
</div>

wap_web/templates/wapApp/activate.html
{% load staticfiles %}
<!doctype html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title></title>
<script type="text/javascript" src="{% static 'js/jquery-1.10.1.min.js' %}"></script>

    <link rel="http://192.168.2.34:8000/static/css/layer.css201803261743">
{#    css路径错误，可能是加载了缓存的css文件#}
    <link rel="http://res.layui.com/layui/dist/css/layui201803261743.css">
    <script src="{% static 'js/layui201803261743.js' %}"></script>
    <script src="{% static 'js/layer201803261743.js' %}"></script>

<style>
    body{
	margin:0;
	color:#6a6f8c;
	background:#c8c8c8;
	font:600 16px/18px 'Open Sans',sans-serif;
}
*,:after,:before{box-sizing:border-box}
.clearfix:after,.clearfix:before{content:'';display:table}
.clearfix:after{clear:both;display:block}
a{color:inherit;text-decoration:none;}
input, button {
  outline: none;
  border: none;
}
.login-wrap{
	width:100%;
	margin:auto;
	max-width:525px;
	min-height:670px;
	position:relative;
	background:url(/static/images/bg1.jpg) no-repeat center;
	box-shadow:0 12px 15px 0 rgba(0,0,0,.24),0 17px 50px 0 rgba(0,0,0,.19);
}
.login-html{
	width:100%;
	height:100%;
	position:absolute;
	padding:90px 30px 50px 30px;
	background:rgba(40,57,101,.9);
}
.login-html .sign-in-htm,
.login-html .sign-up-htm{
	top:0;
	left:0;
	right:0;
	bottom:0;
	position:absolute;
	-webkit-transform:rotateY(180deg);
	        transform:rotateY(180deg);
	-webkit-backface-visibility:hidden;
	        backface-visibility:hidden;
	-webkit-transition:all .4s linear;
	        transition:all .4s linear;
}
.login-html .sign-in,
.login-html .sign-up,
.login-form .group .check{
	display:none;
}
.login-html .tab,
.login-form .group .label,
.login-form .group .button{
	text-transform:uppercase;
}
.login-html .tab{
	font-size:22px;
	margin-right:15px;
	padding-bottom:5px;
	margin:0 15px 10px 0;
	display:inline-block;
	border-bottom:2px solid transparent;
}
.login-html .sign-in:checked + .tab,
.login-html .sign-up:checked + .tab{
	color:#fff;
	border-color:#1161ee;
}
.login-form{
	min-height:345px;
	position:relative;
	-webkit-perspective:1000px;
	        perspective:1000px;
	-webkit-transform-style:preserve-3d;
	        transform-style:preserve-3d;
}
.login-form .group{
	margin-bottom:15px;
}
.login-form .group .label,
.login-form .group .input,
.login-form .group .button{
	width:100%;
	color:#fff;
	display:block;
}
.login-form .group .input,
.login-form .group .button{
	border:none;
	padding:15px 20px;
	border-radius:25px;
	background:rgba(255,255,255,.1);
}
.login-form .group input[data-type="password"]{
	text-security:circle;
	-webkit-text-security:circle;
}
.login-form .group .label{
	color:#aaa;
	font-size:12px;
}
.login-form .group .button{
	background:#1161ee;
}
.login-form .group label .icon{
	width:15px;
	height:15px;
	border-radius:2px;
	position:relative;
	display:inline-block;
	background:rgba(255,255,255,.1);
}
.login-form .group label .icon:before,
.login-form .group label .icon:after{
	content:'';
	width:10px;
	height:2px;
	background:#fff;
	position:absolute;
	-webkit-transition:all .2s ease-in-out 0s;
	        transition:all .2s ease-in-out 0s;
}
.login-form .group label .icon:before{
	left:3px;
	width:5px;
	bottom:6px;
	-webkit-transform:scale(0) rotate(0);
	    -ms-transform:scale(0) rotate(0);
	        transform:scale(0) rotate(0);
}
.login-form .group label .icon:after{
	top:6px;
	right:0;
	-webkit-transform:scale(0) rotate(0);
	    -ms-transform:scale(0) rotate(0);
	        transform:scale(0) rotate(0);
}
.login-form .group .check:checked + label{
	color:#fff;
}
.login-form .group .check:checked + label .icon{
	background:#1161ee;
}
.login-form .group .check:checked + label .icon:before{
	-webkit-transform:scale(1) rotate(45deg);
	    -ms-transform:scale(1) rotate(45deg);
	        transform:scale(1) rotate(45deg);
}
.login-form .group .check:checked + label .icon:after{
	-webkit-transform:scale(1) rotate(-45deg);
	    -ms-transform:scale(1) rotate(-45deg);
	        transform:scale(1) rotate(-45deg);
}
.login-html .sign-in:checked + .tab + .sign-up + .tab + .login-form .sign-in-htm{
	-webkit-transform:rotate(0);
	    -ms-transform:rotate(0);
	        transform:rotate(0);
}
.login-html .sign-up:checked + .tab + .login-form .sign-up-htm{
	-webkit-transform:rotate(0);
	    -ms-transform:rotate(0);
	        transform:rotate(0);
}

.hr{
	height:2px;
	margin:60px 0 50px 0;
	background:rgba(255,255,255,.2);
}
.foot-lnk{
	text-align:center;
}
</style>
</head>
<body>
<div class="jq22-container">
	<div class="login-wrap">
		<div class="login-html">
			<input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">登录</label>
			<input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab"></label>
			<div class="login-form">
				<div class="sign-in-htm">
                    <form role="form" id="activeform" action="{% url 'wapApp:activeUser' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="user_id" value="{{ user_info.id }}">
                        <input type="hidden" name="add_date" value="{{ user_info.add_date }}">
                        <input type="hidden" name="username" value="{{ user_info.username }}">
                        <input type="hidden" name="password" value="{{ user_info.password }}">
					<div class="group">
						<label for="user" class="label">用户名&nbsp;<span id="userErr"></span></label>
						<input id="activeuser" type="text" name="activeuser" class="input" required>
					</div>
					<div class="group">
						<label for="pass" class="label">密码&nbsp;<span id="passErr"></span></label>
						<input id="activepassword" name="activepassword" type="password" class="input" data-type="password" required>
					</div>
					<div class="group">
						<input type="submit" id="active" class="button" value="登录">
					</div>
                    </form>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
     $(document).ready(function() {
     $("#active").click(function () {

         $.ajax({
             url: "/wapApp/activeUser/",
             type: "POST",
             data: $("#activeform").serialize(),
             dataType: "JSON",
             success: function (d) {
                 if (d.status == 'improve') {
                     alert(d.msg)
                     window.location.reload()
                 }
                 if (d.status == 'error') {
                     alert(d.msg)
                     window.location.reload()
                 }
                 if (d.status == 'overtime') {
                     alert(d.msg)
                     window.location.href("{% url 'wapApp:user' %}")
                 }
                 if (d.status == 'activesuccess') {
                     alert(d.msg)
                     window.location.replace("http://192.168.2.34:8000/wapApp/user")
                 }

             }
         })

     })
    })
</script>
</body>
</html>

wap_web/templates/wapApp/contact.html
{% load staticfiles %}
<div class="pages">
  <div data-page="projects" class="page no-toolbar no-navbar">
    <div class="page-content">

     <div class="navbarpages">
       <div class="navbar_home_link"><a href="#" data-panel="left" class="open-panel"><img src="{% static 'images/icons/white/user.png' %}" alt="" title="" /></a></div>
       <div class="navbar_page_center">About</div>
            <div class="menu_open_icon_white"><a href="{% url 'wapApp:index' %}"><img src="{% static 'images/menu_open.png' %}" alt="" title="" /></a></div>
     </div>
     <div id="pages_maincontent">

      <h2 class="page_subtitle">Get in touch</h2>

            <h2 id="Note"></h2>
            <div class="contactform">
            <form class="cmxform" id="ContactForm" method="post" action="">
            <label>Name:</label>
            <input type="text" name="ContactName" id="ContactName" value="" class="form_input required" />
            <label>Email:</label>
            <input type="text" name="ContactEmail" id="ContactEmail" value="" class="form_input required email" />
            <label>Message:</label>
            <textarea name="ContactComment" id="ContactComment" class="form_textarea textarea required" rows="" cols=""></textarea>
            <input type="submit" name="submit" class="form_submit" id="submit" value="Send" />
            <input class="" type="hidden" name="to"  value="youremail@yourwebsite.com" />
            <input class="" type="hidden" name="subject" value="Contacf form message" />
            <label id="loader" style="display:none;"><img src="{% static 'images/loader.gif' %}" alt="Loading..." id="LoadingGraphic" /></label>
            </form>
            </div>

      <h3>Our Location</h3>
<iframe src="{% url 'wapApp:ditu' %}" width="100%" height="100%" frameborder="0" style="border:0">

      </iframe>
      <blockquote>
      Adress: New York 23066 / Pacific Street / Brooklyn <br />
      Email: email@yourwebsite.com <br />
      Mobile: +900 456 567 77
      </blockquote>

      <div class="call_button"><a href="">Call Us Now!</a></div>

      </div>


    </div>
  </div>
</div>

wap_web/templates/wapApp/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}" />
<link rel="apple-touch-startup-image" href="{% static 'images/apple-touch-startup-image-320x460.png' %}" />
<title>wap页面</title>
<link rel="stylesheet" href="{% static 'css/framework7.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/swipebox.css' %}" />
</head>
<body id="mobile_wrap">
    <div class="statusbar-overlay"></div>

    <div class="panel-overlay"></div>

    <div class="panel panel-left panel-cover">
      <div class="user_login_info">
			<div class="user_thumb"><img src="{% static 'images/photos/photo8.jpg' %}" alt="" title="" /></div>
			<h2>您好&nbsp;{{ request.session.username  }}</h2>
			<p>编辑您的账户设置</p>
              <nav class="list-nav-small">
                <ul>
                  <li class="about-icon-small"><a href="about.html" class="close-panel">Profile</a></li>
                  <li class="tools-icon-small"><a href="features.html" class="close-panel">Settings</a></li>
                  <li class="lock-icon-small"><a href="features.html" class="close-panel">Account</a></li>
                  <li class="envelope-icon-small"><a href="features.html" class="close-panel">Messages</a></li>
                  <li class="logout-icon-small"><a href="{% url 'wapApp:logout' %}"  class="close-panel">Logout</a></li>
                </ul>
              </nav>
      </div>
    </div>

    <div class="views">

      <div class="view view-main">


        <div class="pages navbar-through toolbar-through">

          <div data-page="index" class="page homepage">
            <div class="page-content">
            
                  <!-- Slider -->
                  <div class="swiper-container swiper-init" data-effect="slide" data-pagination=".swiper-pagination">
                    <div class="swiper-wrapper">
                    
                      <div class="swiper-slide" >
                          <nav class="list-nav">
                            <ul>
                              <li class="about-icon"><a href="{% url 'wapApp:about' %}">关于</a></li>
                              <li class="responsive-icon"><a href="#" data-panel="left" class="open-panel">个人中心</a></li>
                              <li class="features-icon"><a href="{% url 'wapApp:features' %}">应用</a></li>
                              <li class="photos-icon"><a href="{% url 'wapApp:photos' %}">照片墙</a></li>
                              <li class="video-icon"><a href="{% url 'wapApp:security' %}">视频</a></li>
                              <li class="blog-icon"><a href="blog.html">博客</a></li>
                              <li class="toogle-icon"><a href="toogle.html">Toogle</a></li>
                              <li class="docs-icon"><a href="tabs.html">Tabs</a></li>
                              <li class="contact-icon"><a href="{% url 'wapApp:contact' %}">邮件</a></li>
                            </ul>
                          </nav>
                      </div>
                      
                      <div class="swiper-slide">
                          <nav class="list-nav-half">
                            <ul>
                              <li class="blog-icon-half"><a href="blog.html">Blog</a></li>
                              <li class="toogle-icon-half"><a href="toogle.html">Toogle</a></li>
                              <li class="docs-icon-half"><a href="tabs.html">Tabs</a></li>
                              <li class="contact-icon-half"><a href="{% url 'wapApp:contact' %}">Contact</a></li>
                            </ul>
                          </nav>
                      </div> 
                      <div class="swiper-slide">
                          <span>CALL <br /> US NOW</span>
                          <span class="subtitle">get in touch</span>
                          <a href="" class="swiper_read_more">click to call now!</a>                      
                      </div>
                          
                    </div>
                    <div class="swiper-pagination"></div>
                  </div>     
                           
            </div>
          </div>
        </div>
      
        <div class="toolbar">
              <div class="toolbar-inner" style="background-color:#0f8587 ">
              <ul class="toolbar_icons icons_4row">
                   <li><a href="{% url 'wapApp:index' %}"><img src="{% static 'images/icons/white/home.png' %}" alt="" title="" /></a></li>
                   <li><a href="{% url 'wapApp:security' %}"><img src="{% static 'images/icons/white/lock.png' %}" alt="" title="" /></a></li>
                   <li><a href="#" data-popup=".popup-social" class="open-popup"><img src="{% static 'images/icons/white/heart.png' %}" alt="" title="" /></a></li>
                   <li><a href="{% url 'wapApp:user' %}" ><img src="{% static 'images/icons/white/user.png' %}" alt="" title="" /></a></li>
               </ul>
              </div>
        </div>
      </div>
    </div>

    <!-- About Popup -->
    <!-- Services Popup -->
    <div class="popup popup-social">
    <div class="content-block">
      <h4>Social Share</h4>
      <p>Share icons solution that allows you share and increase your social popularity.</p>
      <ul class="social_share">
      <li><a href="#"><img src="{% static 'images/icons/white/twitter.png' %}" alt="" title="" /></a></li>
      <li><a href="#"><img src="{% static 'images/icons/white/facebook.png' %}" alt="" title="" /></a></li>
      <li><a href="#"><img src="{% static 'images/icons/white/googleplus.png' %}" alt="" title="" /></a></li>
      <li><a href="#"><img src="{% static 'images/icons/white/dribbble.png' %}" alt="" title="" /></a></li>
      <li><a href="#"><img src="{% static 'images/icons/white/linkedin.png' %}" alt="" title="" /></a></li>
      <li><a href="#"><img src="{% static 'images/icons/white/pinterest.png' %}" alt="" title="" /></a></li>
      </ul>
      <div class="close_popup_button"><a href="#" class="close-popup">Close</a></div>
    </div>
    </div>
	
	
<script type="text/javascript" src="{% static 'js/jquery-1.10.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.validate.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/framework7.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/my-app.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.swipebox.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.fitvids.js' %}"></script>
<script type="text/javascript" src="{% static 'js/email.js' %}"></script>



</body>
</html>

wap_web/templates/wapApp/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

wap_web/templates/wapApp/userCenter.html
{% load staticfiles %}
<html>
<head></head>
<body>
<div class="pages">
  <div data-page="projects" class="page no-toolbar no-navbar">
    <div class="page-content" >
<iframe src="{% url 'wapApp:base' %}" width="100%" height="100%" frameborder="0" scrolling="auto" style="border:0"></iframe>

    </div>
  </div>
</div>

</body>
</html>