project/project/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('projectApp.urls'))
]

project/projectApp/urls.py
from django.conf.urls import url

from . import views
app_name = 'projectApp'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^ditu/$', views.ditu, name='ditu'),
]

project/projectApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

project/projectApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'../templates/projectApp/index.html')
def ditu(request):
    return render(request,'../templates/projectApp/ditu.html')

project/templates/projectApp/ditu.html
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
    <style type="text/css">
      body,html,#container{
        height: 100%;
        margin: 0px;
      }
    </style>
    <title>快速入门</title>
  </head>
  <body>
    <div id="container" tabindex="0"></div>
  <script type="text/javascript" src="http://webapi.amap.com/maps?v=1.4.4&key=2741ff0b1e1a0df2bf5217baf70765bd&plugin=AMap.ToolBar"></script>

    <script type="text/javascript">
        var map = new AMap.Map('container',{
            resizeEnable: true,
            zoom: 10,
            center: [116.480983, 40.0958]
        });
    </script>
  </body>
</html>

project/templates/projectApp/index.html
HTML

<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
    <style type="text/css">
      body,html,#container{
        height: 100%;
        margin: 0px;
      }
    </style>
    <title>快速入门</title>
  </head>
  <body>
  <a href="{% url 'projectApp:ditu' %}">点击</a>
  </body>
</html>