backstage_management/commonApp/urls.py
from django.conf.urls import url

from . import views
app_name = 'commonApp'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^regist/$', views.regist, name='regist'),
    url(r'^logout/$', views.logout, name='logout'),

]

backstage_management/jingDong/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from commonApp import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('commonApp.urls'))
]

backstage_management/commonApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import admin
from django.db import models
import django.utils.timezone as timezone
# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=100)
    sex = models.IntegerField(default=0)
    phone = models.CharField(max_length=30,unique=True)
    email = models.EmailField(max_length=30)
    note = models.CharField(max_length=100)
    admin_role = models.CharField(max_length=50, default='保密')
    add_date = models.DateTimeField('保存日期', default=timezone.now)
    mod_date = models.DateTimeField('最后修改日期',null=True)

backstage_management/commonApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import JsonResponse
# PIL是python2版本的图像处理库，不过现在用Pillow比PIL强大，是python3的处理库
from PIL import Image, ImageDraw, ImageFont
from django.http import HttpResponse
from django.shortcuts import render, redirect
import random
from io import BytesIO

from django.shortcuts import render, render_to_response
from django import forms
from django.http.response import HttpResponseRedirect
import re
from django.contrib.auth import authenticate
from .models import User
import django.utils.timezone as timezone

# Create your views here.
def index(request):
   if request.session.get('username'):
        return render(request,'../templates/commonApp/index.html')
   else:
       return render(request, '../templates/commonApp/login.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['userpwd']

        info = User.objects.filter(username=username, password=password)
        if info.exists():
            info_dict = {'username': username}
            request.session['username']=username
            return render(request, '../templates/commonApp/index.html',{'info_dict': info_dict})
        else:
            return render(request, '../templates/commonApp/login.html',{'errors': '用户名或密码不正确'})
    else:
        return render(request, '../templates/commonApp/login.html')
def regist(request):
    user = User.objects.filter(username=request.POST['user-name'])
    if user.exists():
        return render(request,'../templates/commonApp/index.html',{'errors': '用户已存在'})
    else:
        username = request.POST['user-name']
        password = request.POST['userpassword']
        sex = request.POST.get('sex')
        phone = request.POST['user-tel']
        email = request.POST['email']
        add_date = timezone.now()
        note = request.POST['note']
        admin_role = request.POST.get('admin-role')
        User.objects.create(username=username, password=password, sex=sex, phone=phone, email=email, add_date=add_date, note=note, admin_role=admin_role)
        return render('../templates/commonApp/login.html')
def logout(request):
    del request.session['username']
    return render(request, '../templates/commonApp/login.html')

backstage_management/templates/commonApp/home.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'css/index.css'%}"/>
        <link rel="stylesheet" href="{% static 'assets/css/ace.min.css'%}" />
        <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css'%}" />
        <link rel="stylesheet" href="{% static 'assets/css/codemirror.css'%}" />
		<!--[if IE 7]>
		 <link rel="stylesheet" href="{% static 'assets/css/font-awesome-ie7.min.css'%}" />
		<![endif]-->
        <!--[if lte IE 8]>
		   <link rel="stylesheet" href="{% static 'assets/css/ace-ie.min.css'%}" />
		<![endif]-->
			<script src="{% static 'assets/js/ace-extra.min.js'%}"></script>
		<!--[if lt IE 9]>
		<script src="{% static 'assets/js/html5shiv.js'%}"></script>
		<script src="{% static 'assets/js/respond.min.js'%}"></script>
		<![endif]-->
        		<!--[if !IE]> -->
		<script src="{% static 'js/jquery.min.js'%}"></script>
		<!-- <![endif]-->
           	<script src="{% static 'assets/dist/echarts.js'%}"></script>
        <script src="{% static 'assets/js/bootstrap.min.js'%}"></script>
       <title></title>
       </head>		
<body>
<div class="page-content clearfix">
 <div class="alert alert-block alert-success">
  <button type="button" class="close" data-dismiss="alert"><i class="icon-remove"></i></button>
  <i class="icon-ok green"></i>欢迎使用<strong class="green">后台管理系统<small>(v1.2)</small></strong>,你本次登陆时间为2016年7月12日13时34分，登陆IP:192.168.1.110.
 </div>
 <div class="state-overview clearfix" style="margin-left:-12px;">
      <div class="col-lg-3 col-sm-6">
          <section class="panel">
          <a href="#" title="商城会员">
              <div class="symbol terques">
                 <i class="icon-user"></i>
              </div>
              <div class="value">
                  <h1>34522</h1>
                  <p>商城用户</p>
              </div>
              </a>
          </section>
      </div>
      <div class="col-lg-3 col-sm-6">
          <section class="panel">
              <div class="symbol red">
                  <i class="icon-tags"></i>
              </div>
              <div class="value">
                  <h1>140</h1>
                  <p>分销记录</p>
              </div>
          </section>
      </div>
      <div class="col-lg-3 col-sm-6">
          <section class="panel">
              <div class="symbol yellow">
                  <i class="icon-shopping-cart"></i>
              </div>
              <div class="value">
                  <h1>345</h1>
                  <p>商城订单</p>
              </div>
          </section>
      </div>
      <div class="col-lg-3 col-sm-6">
          <section class="panel">
              <div class="symbol blue">
                  <i class="icon-bar-chart"></i>
              </div>
              <div class="value">
                  <h1>￥34,500</h1>
                  <p>交易记录</p>
              </div>
          </section>
      </div>
 </div>
             <!--实时交易记录-->
 <div class="clearfix" style="margin-top:-400px;">
     <div class="Order_Statistics ">
      <div class="title_name">订单统计信息</div>
       <table class="table table-bordered">
       <tbody>
       <tr><td class="name">未处理订单：</td><td class="munber"><a href="#">0</a>&nbsp;个</td></tr>
       <tr><td class="name">待发货订单：</td><td class="munber"><a href="#">10</a>&nbsp;个</td></tr>
       <tr><td class="name">待结算订单：</td><td class="munber"><a href="#">13</a>&nbsp;个</td></tr>
       <tr><td class="name">已成交订单数：</td><td class="munber"><a href="#">26</a>&nbsp;个</td></tr>
       <tr><td class="name">交易失败：</td><td class="munber"><a href="#">26</a>&nbsp;个</td></tr>
       </tbody>
      </table>
     </div>
     <div class="Order_Statistics" style="margin-left: -2px;">
      <div class="title_name">商品统计信息</div>
       <table class="table table-bordered">
       <tbody>
       <tr><td class="name">商品总数：</td><td class="munber"><a href="#">340</a>&nbsp;个</td></tr>
       <tr><td class="name">回收站商品：</td><td class="munber"><a href="#">10</a>&nbsp;个</td></tr>
       <tr><td class="name">上架商品：</td><td class="munber"><a href="#">13</a>&nbsp;个</td></tr>
       <tr><td class="name">下架商品：</td><td class="munber"><a href="#">26</a>&nbsp;个</td></tr>
       <tr><td class="name">商品评论：</td><td class="munber"><a href="#">21s6</a>&nbsp;条</td></tr>

       </tbody>
      </table>
     </div>
     <div class="Order_Statistics" style="margin-left: -2px;">
      <div class="title_name">会员登陆统计信息</div>
       <table class="table table-bordered">
       <tbody>
       <tr><td class="name">注册会员登陆：</td><td class="munber"><a href="#">3240</a>&nbsp;次</td></tr>
       <tr><td class="name">新浪会员登陆：</td><td class="munber"><a href="#">1130</a>&nbsp;次</td></tr>
       <tr><td class="name">支付宝登陆：</td><td class="munber"><a href="#">1130</a>&nbsp;次</td></tr>
       <tr><td class="name">QQ会员登陆：</td><td class="munber"><a href="#">1130</a>&nbsp;次</td></tr>
       </tbody>
      </table>
     </div>
         <!--<div class="t_Record">
           <div id="main" style="height:300px; overflow:hidden; width:100%; overflow:auto" ></div>
          </div> -->
{#     <div class="news_style" style="float:right;margin-top: -213px;margin-left: 2px;" >#}
{#      <div class="title_name">最新消息</div>#}
{#      <ul class="list">#}
{#       <li><i class="icon-bell red"></i><a href="#">后台系统找那个是开通了。</a></li>#}
{#       <li><i class="icon-bell red"></i><a href="#">6月共处理订单3451比，作废为...</a></li>#}
{#       <li><i class="icon-bell red"></i><a href="#">后台系统找那个是开通了。</a></li>#}
{#       <li><i class="icon-bell red"></i><a href="#">后台系统找那个是开通了。</a></li>#}
{#       <li><i class="icon-bell red"></i><a href="#">后台系统找那个是开通了。</a></li>#}
{#      </ul>#}
{#     </div>#}
 </div>
 <!--记录-->
 <div class="clearfix" style="margin-top: -40px;text-align: center;">
  <div class="home_btn">
     <div>
     <a href="picture-add.html"  title="添加商品" class="btn  btn-info btn-sm no-radius">
     <i class="bigger-200"><img src="{% static 'imgs/icon-addp.png' %}" /></i>
     <h5 class="margin-top">添加商品</h5>
     </a>
     <a href="Category_Manage.html"  title="产品分类" class="btn  btn-primary btn-sm no-radius">
     <i class="bigger-200"><img src="{% static 'imgs/icon-cpgl.png' %}" /></i>
     <h5 class="margin-top">产品分类</h5>
     </a>
     <a href="admin_info.html"  title="个人信息" class="btn  btn-success btn-sm no-radius">
     <i class="bigger-200"><img src="{% static 'imgs/icon-grxx.png' %}" /></i>
     <h5 class="margin-top">个人信息</h5>
     </a>
     <a href="Systems.html"  title="系统设置" class="btn  btn-info btn-sm no-radius">
     <i class="bigger-200"><img src="{% static 'imgs/xtsz.png' %}" /></i>
     <h5 class="margin-top">系统设置</h5>
     </a>
     <a href="Order_handling.html"  title="商品订单" class="btn  btn-purple btn-sm no-radius">
     <i class="bigger-200"><img src="{% static 'imgs/icon-gwcc.png' %}" /></i>
     <h5 class="margin-top">商品订单</h5>
     </a>
     <a href="picture-add.html"  title="添加广告" class="btn  btn-pink btn-sm no-radius">
     <i class="bigger-200"><img src="{% static 'imgs/icon-ad.png' %}" /></i>
     <h5 class="margin-top">添加广告</h5>
     </a>
      <a href="article_add.html"  title="添加文章" class="btn  btn-info btn-sm no-radius">
     <i class="bigger-200"><img src="{% static 'imgs/icon-addwz.png' %}" /></i>
     <h5 class="margin-top">添加文章</h5>
     </a>
     </div>
  </div>

 </div>

     </div>
</body>
</html>
<script type="text/javascript">
//面包屑返回值
var index = parent.layer.getFrameIndex(window.name);
parent.layer.iframeAuto(index);
$('.no-radius').on('click', function(){
	var cname = $(this).attr("title");
	var chref = $(this).attr("href");
	var cnames = parent.$('.Current_page').html();
	var herf = parent.$("#iframe").attr("src");
    parent.$('#parentIframe').html(cname);
    parent.$('#iframe').attr("src",chref).ready();;
	parent.$('#parentIframe').css("display","inline-block");
	parent.$('.Current_page').attr({"name":herf,"href":"javascript:void(0)"}).css({"color":"#4c8fbd","cursor":"pointer"});
	//parent.$('.Current_page').html("<a href='javascript:void(0)' name="+herf+" class='iframeurl'>" + cnames + "</a>");
    parent.layer.close(index);
	
});
     $(document).ready(function(){
		 
		  $(".t_Record").width($(window).width()-640);
		  //当文档窗口发生改变时 触发  
    $(window).resize(function(){
		 $(".t_Record").width($(window).width()-640);
		});
 });
	 
	 
 </script>   

backstage_management/templates/commonApp/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
		<link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css'%}" />
		<!--[if IE 7]>
		  <link rel="stylesheet" href="{% static 'assets/css/font-awesome-ie7.min.css'%}" />
		<![endif]-->
		<link rel="stylesheet" href="{% static 'assets/css/ace.min.css'%}" />
		<link rel="stylesheet" href="{% static 'assets/css/ace-rtl.min.css'%}" />
		<link rel="stylesheet" href="{% static 'assets/css/ace-skins.min.css'%}" />
        <link rel="stylesheet" href="{% static 'css/index.css'%}"/>
		<!--[if lte IE 8]>
		  <link rel="stylesheet" href="{% static 'assets/css/ace-ie.min.css'%}" />
		<![endif]-->
		<script src="{% static 'assets/js/ace-extra.min.js'%}"></script>
		<!--[if lt IE 9]>
		<script src="{% static 'assets/js/html5shiv.js'%}"></script>
		<script src="{% static 'assets/js/respond.min.js'%}"></script>
		<![endif]-->
		<script src="{% static 'js/jquery-1.9.1.min.js'%}"></script>
        <script src="{% static 'assets/layer/layer.js' %}" type="text/javascript"></script>
    <script>
       var code;
    function createCode(){
        //首先默认code为空字符串
        code = '';
        //设置长度，这里看需求，我这里设置了4
        var codeLength = 4;
        var codeV = document.getElementById('code');
        //设置随机字符
        var random = new Array(0,1,2,3,4,5,6,7,8,9,'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R', 'S','T','U','V','W','X','Y','Z');
        //循环codeLength 我设置的4就是循环4次
        for(var i = 0; i < codeLength; i++){
            //设置随机数范围,这设置为0 ~ 36
             var index = Math.floor(Math.random()*36);
             //字符串拼接 将每次随机的字符 进行拼接
             code += random[index];
        }
        //将拼接好的字符串赋值给展示的Value
        codeV.innerHTML = code;
    }
       window.onload = function (){

        createCode();
    }
{#   function validate(){#}
{#        var oValue = document.getElementById('input').value.toUpperCase();#}
{#        if(oValue ==0){#}
{#            alert('请输入验证码');#}
{#        }else if(oValue != code){#}
{#            alert('验证码不正确，请重新输入');#}
{#            oValue = ' ';#}
{#            createCode();#}
{#        }else{#}
{#            window.open('http://www.baidu.com','_self');#}
{#        }#}
{#    }#}
    </script>
<title>登陆</title>
</head>

<body class="login-layout Reg_log_style">
<div class="logintop">    
    <span>欢迎后台管理界面平台</span>    
    <ul>
    <li><a href="#">返回首页</a></li>
    <li><a href="#">帮助</a></li>
    <li><a href="#">关于</a></li>
    </ul>    
    </div>
    <div class="loginbody">
<div class="login-container">
	<div class="center">
	     <img src="{% static 'imgs/logo1.png' %}" />
							</div>

							<div class="space-6"></div>

							<div class="position-relative">
								<div id="login-box" class="login-box widget-box no-border visible">
									<div class="widget-body">
										<div class="widget-main">
											<h4 class="header blue lighter bigger">
												<i class="icon-coffee green"></i>
												管理员登陆
											</h4>

											<div class="login_icon"><img src="{% static 'imgs/login.png' %}" /></div>

											<form class="" action="{% url 'commonApp:login' %}" method="post">
												 {% csrf_token %}
                                                <fieldset>
										<ul>
   <li class="frame_style form_error"><label class="user_icon"></label><input name="username" type="text"  id="username" placeholder="用户名"/></li>
   <li class="frame_style form_error"><label class="password_icon"></label><input name="userpwd" type="password"   id="userpwd" placeholder="密码"/></li>
   <li class="frame_style form_error"><label class="Codes_icon"></label><input name="验证码" type="text" id="Codes_text" placeholder="验证码"/><div id="code" style="font-size:20px;text-align: center" class="Codes_region" onclick="createCode()"></div></li>
   
  </ul>
													<div class="space"></div>

													<div class="clearfix">
														<label class="inline">
															<input type="checkbox" class="ace">
															<span class="lbl">保存密码</span>
														</label>

														<input type="submit" class="width-35 pull-right btn btn-sm btn-primary" id="login_btn" value="登&nbsp;&nbsp;陆">
															<i class="icon-key"></i>
															登陆
														</input>
													</div>

													<div class="space-4"></div>
												</fieldset>
											</form>

											<div class="social-or-login center">
												<span class="bigger-110">通知</span>
											</div>

											<div class="social-login center">
											本网站系统不再对IE8以下浏览器支持，请见谅。
											</div>
										</div><!-- /widget-main -->

										<div class="toolbar clearfix">
											

											
										</div>
									</div><!-- /widget-body -->
								</div><!-- /login-box -->
							</div><!-- /position-relative -->
						</div>
                        </div>
                        <div class="loginbm">版权所有  2016  <a href="">南京思美软件系统有限公司</a> </div><strong></strong>
</body>
</html>
<script>

   var code;
    function createCode(){
        //首先默认code为空字符串
        code = '';
        //设置长度，这里看需求，我这里设置了4
        var codeLength = 4;
        var codeV = document.getElementById('code');
        //设置随机字符
        var random = new Array(0,1,2,3,4,5,6,7,8,9,'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R', 'S','T','U','V','W','X','Y','Z');
        //循环codeLength 我设置的4就是循环4次
        for(var i = 0; i < codeLength; i++){
            //设置随机数范围,这设置为0 ~ 36
             var index = Math.floor(Math.random()*36);
             //字符串拼接 将每次随机的字符 进行拼接
             code += random[index];
        }
        //将拼接好的字符串赋值给展示的Value
        codeV.innerHTML = code;
    }
       window.onload = function (){

        createCode();
    }


{#$('#login_btn').on('click', function(){#}
{#	     var num=0;#}
{#		 var str="";#}
{##}
{#     $("input[type$='text'],input[type$='password']").each(function(n){#}
{#          if($(this).val()=="")#}
{#          {#}
{#			   layer.alert(str+=""+$(this).attr("name")+"不能为空！\r\n",{#}
{#                title: '提示框',				#}
{#				icon:0,								#}
{#          });#}
{#		    num++;#}
{#            return false;            #}
{#          }#}
{#		 });#}
{##}
{#          if($('#username').val()==""){#}
{#            layer.alert("用户名不能为空！\r\n",{#}
{#                title: '提示框',#}
{#				icon:0,#}
{#          });#}
{#            return false;#}
{#        }#}
{#         if($('#userpwd').val()==''){#}
{#            layer.alert("密码不能为空！\r\n",{#}
{#                title: '提示框',#}
{#				icon:0,#}
{#          });#}
{#            return false;#}
{#        }#}
{#         if($('#Codes_text').val()==''){#}
{#            layer.alert("验证码不能为空！\r\n",{#}
{#                title: '提示框',#}
{#				icon:0,#}
{#          });#}
{#            return false;#}
{#        }#}
{#          console.log($('#Codes_text').val())#}
{#        console.log(code)#}
{##}
{##}
{#        if($('#Codes_text').val().toUpperCase()!=code){#}
{#            layer.alert("验证码错误！\r\n",{#}
{#                title: '提示框',#}
{#				icon:0,#}
{#          });#}
{#            return false;#}
{#        }#}
{#		  if(num>0){  return false;}#}
{#          else{#}
{#	          location.href="{% url 'commonApp:login' %}";#}
{#			   layer.close(index);#}
{#		  }#}
{##}
{#	});#}
{#  $(document).ready(function(){#}
{#	 $("input[type='text'],input[type='password']").blur(function(){#}
{#        var $el = $(this);#}
{#        var $parent = $el.parent();#}
{#        $parent.attr('class','frame_style').removeClass(' form_error');#}
{#        if($el.val()==''){#}
{#            $parent.attr('class','frame_style').addClass(' form_error');#}
{#        }#}
{#    });#}
{#	$("input[type='text'],input[type='password']").focus(function(){#}
{#		var $el = $(this);#}
{#        var $parent = $el.parent();#}
{#        $parent.attr('class','frame_style').removeClass(' form_errors');#}
{#        if($el.val()==''){#}
{#            $parent.attr('class','frame_style').addClass(' form_errors');#}
{#        } else{#}
{#			 $parent.attr('class','frame_style').removeClass(' form_errors');#}
{#		}#}
{#		});#}
{#	  })#}

</script>

backstage_management/templates/commonApp/otherLoginModel/fixLogin.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" >
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Alley Signup & Signin Form Responsive Widget Template  :: 小贝壳网站模板</title>
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Alley Signup & Signin Form Tab Form,Login Forms,Sign up Forms,Registration Forms,News letter Forms,Elements"./>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<script src="{% static 'js/easyResponsiveTabs.js' %}" type="text/javascript"></script>
				<script type="text/javascript">
					$(document).ready(function () {
						$('#horizontalTab').easyResponsiveTabs({
							type: 'default', //Types: default, vertical, accordion
							width: 'auto', //auto or any width like 600px
							fit: true   // 100% fit in a container
						});
					});
				   </script>
</head>
<body>
	<h1> Alley Signup & Signin Form </h1>

<div class="main-content">
	<div class="sap_tabs">

		<div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">

			  <ul>
			  	  <li class="resp-tab-item" aria-controls="tab_item-0" role="tab"><span>Sign in</span></li>
				  <li class="resp-tab-item" aria-controls="tab_item-1" role="tab"><span>Sign up</span></li>

			  </ul>
			  <!---->



			<div class="tab-2 resp-tab-content" aria-labelledby="tab_item-1">
				<div class="facts">
					<div class="register">
						<form action="{% url 'commonApp:login' %}" method="post">
                            {% csrf_token %}
							<input placeholder="Email Address" class="mail" type="text" required="">
							<input placeholder="Password" class="lock" type="password" required="">
							<div class="sign-up">
								<input type="submit" value="Sign in"/>
							</div>
						</form>
						<h3><a href="#"> Forgot Password</a></h3>
					</div>
				</div>
			</div>
<div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
				<div class="facts">
					<!--login1-->
					<div class="register">
						<form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
								<div class="sign-up">
									<input type="submit" value="Create Account"/>
								</div>
						</form>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>
	 <!--start-copyright-->
   		<div class="copy-right">
   			<div class="wrap">
				<p>&copy; 2016 Alley Signup & Signin Form.  All Rights  Reserved | Design by <a href="http://www.smallseashell.com">.小贝壳网站模板.</a></p>
			</div>
		</div>
	<!--//end-copyright-->

</body>
</html>